server:
  port: ${PORT:0}

token:
  secret: cUQNOIVMSBIR0o1AgypHXGAPICAFIRmQbHwoVQUZjhs=
  expiry: 36000001

spring:
  application:
    name: users-ws
  config:
    import: optional:configserver:http://localhost:8012
    name: config-server
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: developer
    password: dev123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG