server:
  port: ${PORT:0}

spring:
  application:
    name: albums-ws

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  tracing:
    sampling:
      probability: 1.0