server:
  port: ${PORT:0}

spring:
  application:
    name: albums-ws
  config:
    import: optional:configserver:http://localhost:8012
    name: albums-ws
  rabbitmq:
    host: localhost
    port: 5672
    username: developer
    password: dev123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  tracing:
    sampling:
      probability: 1.0