server:
  port: 0

spring:
  application:
    name: account-ws
  devtools:
    restart:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: developer
    password: dev123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka