FROM openjdk:19-jdk-alpine
VOLUME /tmp
COPY photoappkey.jks photoappkey.jks
COPY target/PhotoAppApiConfigServer-0.0.1-SNAPSHOT.jar ConfigServer.jar
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "ConfigServer.jar"]