server:
  port: 8082


token:
  secret: cUQNOIVMSBIR0o1AgypHXGAPICAFIRmQbHwoVQUZjhs=


spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

      routes:
        - id: users-status-check
          uri: lb://users-ws
          predicates:
            - Path=/users/status/check
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

        - id: users-create
          uri: lb://users-ws
          predicates:
            - Path=/users
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie

        - id: users-authenticate
          uri: lb://users-ws
          predicates:
            - Path=/users/authenticate
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie

        - id: users-ops
          uri: lb://users-ws
          predicates:
            - Path=/users/**
            - Method=GET,POST,UPDATE,DELETE
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

        - id: demo-status
          uri: lb://users-ws
          predicates:
            - Path=/demo/status
            - Method=GET,POST
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
