server:
  port: 8082

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

      routes:
        - id: users-status-check
          uri: lb://users-ws
          predicates:
            - Path=/users/status/check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
        - id: users-create
          uri: lb://users-ws
          predicates:
            - Path=/users
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: users-authenticate
          uri: lb://users-ws
          predicates:
            - Path=/users/authenticate
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: demo-status
          uri: lb://users-ws
          predicates:
            - Path=/demo/status
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
