server:
  port: 8010

spring:
  application:
    name: discoveryservice
  rabbitmq:
    host: localhost
    port: 5672
    username: developer
    password: dev123
  security:
    user:
      name: test
      password: test
  config:
    name: discoveryservice
    import: optional:configserver:http://localhost:8012

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    hostname: localhost
